msg = input('Digite algo: \n')
print('O tipo primitivo desse valor é: ',type(msg))
print('Só tem espaço?', msg.isspace())
print('É um número?', msg.isnumeric())
print('É alfabético?', msg.isalpha())
print('É alfanumérico?', msg.isalnum())
print('Está em maíusculas?', msg.isupper())
print('Está em minúsculas?', msg.islower())
print('Está capitalizada?', msg.istitle())